# Generated by Django 3.1.3 on 2021-07-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('tempo', models.IntegerField()),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
